[directory]
truncation_length = 0
truncate_to_repo = false
style = "bold yellow"

[hostname]
ssh_only = false
format = "[$ssh_symbol$hostname]($style) "

[username]
show_always = true
format = "[$user]($style)[@](blue)" 	
style_user = "bold purple"

[git_branch]
style = "bold cyan"

[character]
vimcmd_symbol = "[❮](bold cyan)"

[container]
style = "bold blue"

[docker_context]
disabled = true

[package]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[golang]
disabled = true

[haskell]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
disabled = true

[raku]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vlang]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = true

[nix_shell]
disabled = true

[conda]
disabled = true
