# General format
format = """
$username\
$hostname\
$container\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

# Settings
[directory]
truncation_length = 0
truncate_to_repo = false
style = "bold yellow"

[hostname]
ssh_only = false
ssh_symbol = "🌐"
trim_at = ""
format = "[$ssh_symbol$hostname]($style) "

[username]
show_always = true
format = "[$user]($style) " 	
style_user = "bold purple"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold blue"

[container]
style = "bold blue"

[git_status]
style = "bold cyan"

# Disabled modules
[docker_context]
disabled = true

[package]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[golang]
disabled = true

[haskell]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
format = '[(\($virtualenv\) )]($style)'
style = "bold green"

[raku]
disabled = true

[rlang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[vlang]
disabled = true

[vagrant]
disabled = true

[zig]
disabled = true

[nix_shell]
disabled = true

[conda]
disabled = true

[cmd_duration]
disabled = true
