format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$buf\
$nix_shell\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character"""

[directory]
truncation_length = 0
truncate_to_repo = false

[hostname]
ssh_only = false

[username]
show_always = true

[python]
python_binary = ["python3", "python", "python2"]
symbol = " "
